apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ngx-deploy
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: ngx-pod
        image: nginx
        ports:
        - containerPort: 80