apiVersion: v1
kind: ReplicationController
metadata:
  name: ngx-rc
spec:
  replicas: 5
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: ngx-pod
        image: nginx
        ports:
        - containerPort: 80