---
- hosts: all
  tasks:
  - name: Excecuting ping task
    ping: 
  - name: Excecuting Debug task
    debug:
      msg: "{{ansible_all_ipv4_addresses}}"
    
# ansible > ansible all -m ping
# ansible > ansible-playbook ping.yml