---
- hosts: all
  become: true
  tasks:
  - name: Install apache server
    yum:
      name: httpd
      state: present
  - name: Ensure apache service is runnning
    service:
      name: httpd
      state: started
      enabled: true
       
# ansible > ansible-playbook apache.yml