---
- hosts: webserver
  become: yes
  tasks:
  - name: Install web server
    yum:
      name: "{{webserver_package}}"
      state: present
  - name: Ensure webserver service is runnning
    service:
      name: "{{webserver_package}}"
      state: started
      enabled: true
       
# ansible > ansible-playbook common-host webserver-dynamic-params.yml
# http://ip-172-31-15-143.us-west-2.compute.internal:80