---
#- hosts: webserver
- hosts: local
  become: yes
  tasks:
  - name: Install web server
    yum:
      name: httpd
      state: present
  - name: Ensure webserver service is runnning
    service:
      name: httpd
      state: started
      enabled: true
       
# ansible > ansible-playbook -i common-hosts webserver-switch.yml
# http://ip-172-31-15-143.us-west-2.compute.internal:80